version: "3"
services:
  php-7.2:
    build: docker/php/php-7.2
    volumes:
    - ./:/app
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    links:
      - postgres-9
      - postgres-10
      - postgres-11
      - postgres-12
      - mysql-5
      - mysql-8

  php-7.3:
    build: docker/php/php-7.3
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    links:
      - postgres-9
      - postgres-10
      - postgres-11
      - postgres-12
      - mysql-5
      - mysql-8

  php-7.4:
    build: docker/php/php-7.4
    volumes:
      - ./:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    links:
      - postgres-9
      - postgres-10
      - postgres-11
      - postgres-12
      - mysql-5
      - mysql-8

  postgres-9:
    image: postgres:9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
    - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres-10:
    image: postgres:10
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres-11:
    image: postgres:11
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres-12:
    image: postgres:12
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mysql-5:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  mysql-8:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql

